# Generated by Django 3.1.7 on 2021-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
